name: Generate Snake Graph

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Generate snake SVG
        id: generate-snake
        uses: Platane/snk@master

      - name: Commit and push changes
        uses: actions-js/push@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: .

      - name: Move generated SVG to output directory
        run: mv github-contribution-grid-snake.svg output/

      - name: Push changes to output branch
        uses: actions-js/push@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          directory: output/
